// src/pages/Treatment.js
import React from 'react';
import Sidebar from '../components/Sidebar';
import './Treatment.css';

const Treatment = () => {
  return (
    <div className="main-layout">
      <Sidebar />
      <div className="treatment-container">
        <h1>Treatment Options for Varicose Veins</h1>

        <section className="treatment-section">
          <h2>💡 Laser Treatment</h2>
          <p>Minimally invasive procedure using light energy to close off varicose veins. Often performed in an outpatient setting with quick recovery.</p>
        </section>

        <section className="treatment-section">
          <h2>💉 Sclerotherapy</h2>
          <p>A chemical solution is injected into the vein, causing it to collapse and fade. Best for smaller varicose or spider veins.</p>
        </section>

        <section className="treatment-section">
          <h2>🌡️ Radiofrequency Ablation</h2>
          <p>Uses heat generated by radio waves to close off affected veins. It's minimally invasive and performed under local anesthesia.</p>
        </section>

        <section className="treatment-section">
          <h2>🛠️ Vein Stripping Surgery</h2>
          <p>A traditional surgical approach where larger varicose veins are removed. It may be required in severe or recurrent cases.</p>
        </section>

        <section className="treatment-section">
          <h2>📝 Post-Treatment Care</h2>
          <ul>
            <li>✔️ Wear compression stockings as prescribed</li>
            <li>✔️ Avoid standing for long durations</li>
            <li>✔️ Keep the treated area clean and dry</li>
            <li>✔️ Follow up with your doctor regularly</li>
          </ul>
        </section>
      </div>
    </div>
  );
};

export default Treatment;
